### PR TITLE
Compile against existing shared util if provided

### PR DESCRIPTION
**Pull request by srware**
Only build the shared util library from scratch if it doesn't already exist. This gives the user the option to compile multiple libraries and SDKs against a common version of the library which can co-exist on the same target.

### CODE REVIEW

**Comment by olivierbloch** [comment]
Thanks for your contribution. We are reviewing it and will very certainly merge it in soon.

**Comment by tameraw** [comment]
@srware - We looked at this change and we're concerned that if there is a desire to rebuild the lib and override the current installed version, this change will not allow for that.
Is building with an already built lib a hard requirement for your project?

**Comment by andrew-buckley** [comment]
Hi @srware, we've completed work which I believe accomplishes what you've done here. Please have a look and close this if that is the case.

Thanks,
-Andrew

**Comment by dcristoloveanu** [comment]
@srware 

Closing this as we believe the work is complete. Feel free to open a new issue/PR (or reopen this one) if something more is needed.

Cheers,
/Dan

**Pull request closed without merging**
