### PR TITLE
Convert connection unit tests to umock_c

### PR DESCRIPTION
**Pull request by dcristoloveanu**
Convert connection unit tests to umock_c and use gballoc instead of amqpalloc

### CODE REVIEW

**Comment by tameraw** [comment]
> #include "azure_uamqp_c/amqpalloc.h"

Can this go then? Do you still need it?

---
Refers to: src/connection.c:17 in 6978c7f. [](commit_id = 6978c7fa989b4b33bdb5382d91d3b357f90cbebd, deletion_comment = False)

**Comment by tameraw** [comment]
>     umock_c_reset_all_calls();

Two calls.

---
Refers to: tests/connection_ut/connection_ut.c:599 in 6978c7f. [](commit_id = 6978c7fa989b4b33bdb5382d91d3b357f90cbebd, deletion_comment = False)

**Comment by tameraw** [comment]
>     umock_c_reset_all_calls();

Called twice.

---
Refers to: tests/connection_ut/connection_ut.c:712 in 6978c7f. [](commit_id = 6978c7fa989b4b33bdb5382d91d3b357f90cbebd, deletion_comment = False)

**Comment by tameraw** [comment]
>     umock_c_reset_all_calls();

called twice.

---
Refers to: tests/connection_ut/connection_ut.c:847 in 6978c7f. [](commit_id = 6978c7fa989b4b33bdb5382d91d3b357f90cbebd, deletion_comment = False)

**Comment by tameraw** [comment]
>     umock_c_reset_all_calls();

Twice.

---
Refers to: tests/connection_ut/connection_ut.c:1584 in 6978c7f. [](commit_id = 6978c7fa989b4b33bdb5382d91d3b357f90cbebd, deletion_comment = False)

**Comment by tameraw** [comment]
>     umock_c_reset_all_calls();

twice.

---
Refers to: tests/connection_ut/connection_ut.c:1616 in 6978c7f. [](commit_id = 6978c7fa989b4b33bdb5382d91d3b357f90cbebd, deletion_comment = False)

**Comment by tameraw** [comment]
>     umock_c_reset_all_calls();

duplicate.

---
Refers to: tests/connection_ut/connection_ut.c:1653 in 6978c7f. [](commit_id = 6978c7fa989b4b33bdb5382d91d3b357f90cbebd, deletion_comment = False)

**Comment by tameraw** [comment]
>     umock_c_reset_all_calls();

duplicate

---
Refers to: tests/connection_ut/connection_ut.c:1691 in 6978c7f. [](commit_id = 6978c7fa989b4b33bdb5382d91d3b357f90cbebd, deletion_comment = False)

**Comment by tameraw** [comment]
>     umock_c_reset_all_calls();

Duplicate.

---
Refers to: tests/connection_ut/connection_ut.c:1760 in 6978c7f. [](commit_id = 6978c7fa989b4b33bdb5382d91d3b357f90cbebd, deletion_comment = False)

**Comment by tameraw** [comment]
>     umock_c_reset_all_calls();

Duplicate. I'll stop checking the duplicates here. I'm sure you'll through the rest of the file.

---
Refers to: tests/connection_ut/connection_ut.c:1798 in 6978c7f. [](commit_id = 6978c7fa989b4b33bdb5382d91d3b357f90cbebd, deletion_comment = False)

**Comment by tameraw** [comment]
:shipit:

**Comment by dcristoloveanu** [comment]
> #include "azure_uamqp_c/amqpalloc.h"

Yes, removed.

---
In reply to: [286605028](https://github.com/Azure/azure-uamqp-c/pull/49#issuecomment-286605028) [](ancestors = 286605028)

---
Refers to: src/connection.c:17 in 6978c7f. [](commit_id = 6978c7fa989b4b33bdb5382d91d3b357f90cbebd, deletion_comment = False)

**Comment by dcristoloveanu** [comment]
>     umock_c_reset_all_calls();

Fixed.

---
In reply to: [286606061](https://github.com/Azure/azure-uamqp-c/pull/49#issuecomment-286606061) [](ancestors = 286606061)

---
Refers to: tests/connection_ut/connection_ut.cpp:599 in 6978c7f. [](commit_id = 6978c7fa989b4b33bdb5382d91d3b357f90cbebd, deletion_comment = False)

**Comment by dcristoloveanu** [comment]
>     umock_c_reset_all_calls();

Fixed.

---
In reply to: [286606131](https://github.com/Azure/azure-uamqp-c/pull/49#issuecomment-286606131) [](ancestors = 286606131)

---
Refers to: tests/connection_ut/connection_ut.cpp:712 in 6978c7f. [](commit_id = 6978c7fa989b4b33bdb5382d91d3b357f90cbebd, deletion_comment = False)

**Comment by dcristoloveanu** [comment]
>     umock_c_reset_all_calls();

Fixed.

---
In reply to: [286606183](https://github.com/Azure/azure-uamqp-c/pull/49#issuecomment-286606183) [](ancestors = 286606183)

---
Refers to: tests/connection_ut/connection_ut.cpp:847 in 6978c7f. [](commit_id = 6978c7fa989b4b33bdb5382d91d3b357f90cbebd, deletion_comment = False)

**Comment by dcristoloveanu** [comment]
>     umock_c_reset_all_calls();

Fixed.

---
In reply to: [286606368](https://github.com/Azure/azure-uamqp-c/pull/49#issuecomment-286606368) [](ancestors = 286606368)

---
Refers to: tests/connection_ut/connection_ut.cpp:1584 in 6978c7f. [](commit_id = 6978c7fa989b4b33bdb5382d91d3b357f90cbebd, deletion_comment = False)

**Comment by dcristoloveanu** [comment]
>     umock_c_reset_all_calls();

Fixed.

---
In reply to: [286606393](https://github.com/Azure/azure-uamqp-c/pull/49#issuecomment-286606393) [](ancestors = 286606393)

---
Refers to: tests/connection_ut/connection_ut.cpp:1616 in 6978c7f. [](commit_id = 6978c7fa989b4b33bdb5382d91d3b357f90cbebd, deletion_comment = False)

**Comment by dcristoloveanu** [comment]
>     umock_c_reset_all_calls();

Fixed.

---
In reply to: [286606415](https://github.com/Azure/azure-uamqp-c/pull/49#issuecomment-286606415) [](ancestors = 286606415)

---
Refers to: tests/connection_ut/connection_ut.cpp:1653 in 6978c7f. [](commit_id = 6978c7fa989b4b33bdb5382d91d3b357f90cbebd, deletion_comment = False)

**Comment by dcristoloveanu** [comment]
>     umock_c_reset_all_calls();

Fixed.

---
In reply to: [286606443](https://github.com/Azure/azure-uamqp-c/pull/49#issuecomment-286606443) [](ancestors = 286606443)

---
Refers to: tests/connection_ut/connection_ut.cpp:1691 in 6978c7f. [](commit_id = 6978c7fa989b4b33bdb5382d91d3b357f90cbebd, deletion_comment = False)

**Comment by dcristoloveanu** [comment]
>     umock_c_reset_all_calls();

Fixed.

---
In reply to: [286606613](https://github.com/Azure/azure-uamqp-c/pull/49#issuecomment-286606613) [](ancestors = 286606613)

---
Refers to: tests/connection_ut/connection_ut.cpp:1760 in 6978c7f. [](commit_id = 6978c7fa989b4b33bdb5382d91d3b357f90cbebd, deletion_comment = False)

**Comment by dcristoloveanu** [comment]
>     umock_c_reset_all_calls();

I did, thanks!

---
In reply to: [286606719](https://github.com/Azure/azure-uamqp-c/pull/49#issuecomment-286606719) [](ancestors = 286606719)

---
Refers to: tests/connection_ut/connection_ut.cpp:1798 in 6978c7f. [](commit_id = 6978c7fa989b4b33bdb5382d91d3b357f90cbebd, deletion_comment = False)

**Pull request merged**
